"""Developer-only. Makes the built-in sample sheet (a PLACEHOLDER made with a computer handwriting font,
until a real handwriting photo replaces it) and src/sample.js, which holds it as a data URL so the
"Try with a sample sheet" link works even when the page is opened as a plain file.

    python tools/make_sample.py
"""
import base64
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "tests"))
from make_sheets import make_sheet, photo_effects  # noqa: E402

img = photo_effects(make_sheet("Inkfree.ttf", 120, 1), shadow=0.12, noise=1.5)
img = img.resize((1500, 1950))
buf = io.BytesIO()
img.convert("L").save(buf, "JPEG", quality=62, optimize=True)
data = buf.getvalue()
os.makedirs(os.path.join(ROOT, "examples"), exist_ok=True)
open(os.path.join(ROOT, "examples", "sample-sheet.jpg"), "wb").write(data)
with open(os.path.join(ROOT, "src", "sample.js"), "w", encoding="utf8") as f:
    f.write("// Generated by tools/make_sample.py. A placeholder sample sheet as a data URL.\n")
    f.write('window.HF_SAMPLE = "data:image/jpeg;base64,%s";\n' % base64.b64encode(data).decode("ascii"))
print("sample-sheet.jpg: %d KB" % (len(data) // 1024))
